### ISSUE TITLE
Can I feed FEN string into lozza and get it to play?

### ISSUE THREAD

**Issue by dreemurgithub** [op12no2/lozza#12]

**Comment by op12no2** [comment]
Yes

https://op12no2.github.io/lozza-ui/play.htm?fen=8/8/8/8/4k3/8/8/6QK%20w%20-%20-%200%201

**Comment by dreemurgithub** [comment]
It look great, but how do I do that in code
Can you write some simple document for taking FEN string and return with the moves

**Comment by op12no2** [comment]
Sorry I don't understand what you mean.
