### ISSUE TITLE
no response when losing?

### ISSUE THREAD

**Issue by akinell** [op12no2/lozza#2]
### Error Description:
When setting up a position which is very bad for lozza (i.e. a rook and a queen down) then lozza won't send a bestmove response. Instead, only the following output is sent:
info nodes 0 time 0 nps 0 
info hashfull 0

I am not entirely sure the issue is related only to strongly losing positions.

### Test Case: 
lozza.js build 1.18 in a WebWorker on Chrome.

messages:
uci
ucinewgame
position fen rnb1k3/pppppppp/8/8/8/4P3/PPPP1PPP/RNBQKBNR b KQkq - 0 1
go movetime 500

**Comment by op12no2** [comment]
Hi,

It's an illegal FEN - black has no castling rights.  If you remove the kq
it works.

However I agree it should do something more useful - thanks for the report
- I'll tweak something :)

Cheers,
Colin

**Comment by akinell** [comment]
You are right of course!
I was confused because the fen was generated by chess.js and its validate_fen() method returns "valid: true". Also stockfish.js handles the situation gracefully.

The bug belongs to chess.js, since it doesn't update the castling rights after removing rooks and as there is no way to set castling rights programmatically. It is actually listed in their readme.

thank you for your quick response!

**Comment by op12no2** [comment]
Hi,

Ah I see.  Yes, in hindsight I think it's better for the UI to validate the
position so that the engine can concentrate on a solution (especially at
the end of a game and time is short), so I will not tweak anything in this
instance.

Cheers,
Colin
