### ISSUE TITLE
2.0 or 2.1

### ISSUE THREAD

**Issue by SzotsGabor** [op12no2/lozza#5]
Hi Colin,

You write: 'Around +80 over v2.0 at 60s + 0.6s.' Is that not over v2.1? Just because I am still testing v2.1 and it already shows a handsome gain over v2.0.

Gabor Szots
CCRL

**Comment by op12no2** [comment]
Hi Gabor - I tested against 2.0 - not sure why!

At 60+0.6 2.2 was +84 over 2.0.

At the same time control 2.1 was about +30 over 2.0.

So here 2.2 is about +54 over 2.1.

Please do feel free to ignore 2.2 for a while. I realise I'm messing you
guys around.

Cheers,
Colin

https://coastalchalet.co.uk

**Comment by op12no2** [comment]
ps: i've tweaked the releases to show the gain relative to the previous
release.  so:-

2.1  is +30 over 2.0.
2.2  is +55 over 2.1.

using a TC of 60s + 0.6s.

Cheers,
Colin

https://coastalchalet.co.uk

**Comment by SzotsGabor** [comment]
Thanks Colin. I think I will continue with 2.1 for the moment and postpone 2.2 testing. That does not mean other testers won't test it in the meantime though.
BTW, at the moment we have more than +60 for 2.1 over 2.0. I wonder how that changes after I have submitted my second bunch of games. We'll see by Sunday.

**Comment by op12no2** [comment]
Hi Gabor, understood. Wow +60 is more than I expected :)

Cheers,
Colin

https://coastalchalet.co.uk

**Comment by SzotsGabor** [comment]
Don't tell anyone but I have started a tournament with v2.2 while my test for v2.1 is still running. I'm eager to find out the difference at our time control.

Cheers,
Gabor

**Comment by SzotsGabor** [comment]
It is really unique that you have just released v2.2 and my v2.2 results are about to appear on our blitz list. Is this a time travel?

**Comment by SzotsGabor** [comment]
Is it mandatory to use the latest node? I update mine every now and then but I have not been particularly keen on it.

**Comment by op12no2** [comment]
No but they get better with time, so this way it's auto :)

Cheers,
Colin

https://coastalchalet.co.uk

**Comment by SzotsGabor** [comment]
OK, the only deterrent factor is the size. If I were you, I'd still offer the js as a separate download.

Cheers,
Gabor

**Comment by op12no2** [comment]
Ah OK, I'll tweak it.

PS: Are you finding 2.2 is > 2.1. It's bombing in Grahams D7 tourney!

Cheers,
Colin

https://coastalchalet.co.uk

**Comment by SzotsGabor** [comment]
I'm not sure but the update of the blitz list is imminent so we'll see soon.

**Comment by op12no2** [comment]
OK thx Gabor.

Cheers,
Colin

https://coastalchalet.co.uk

**Comment by SzotsGabor** [comment]
So far results are not particularly encouraging but I expect an improvement after my second, currently running tournament which will bring the average strength of opponents closer to Lozza.

**Comment by op12no2** [comment]
Thanks Gabor,

Yes this seems to be the case on Lichess and Grahams tourneys as well.

However I think I'll have to live with it. It's essentially a bug fix that
should work out in the long run. Specifically I was using the TT in PV
nodes which I stopped doing in 2.2. Which has made it slower but more
accurate. When playing against itself (2.1) that tradeoff works (+50), but
against other engines in general it's no so good. Or something like that.

Cheers,
Colin

https://coastalchalet.co.uk
