### ISSUE TITLE
v2.5 release ?

### ISSUE THREAD

**Issue by tissatussa** [op12no2/lozza#9]
hi, i see you changed some code and also the version number : v2.5 now .. but the main page doesn't show that .. is v2.5 a test and will there be an official release soon ?

**Comment by op12no2** [comment]
Hi Yes, while I'm developing a version, I cache progress in the repo and
publish as an official release when it's ready. Currently no timescale
though. A part-time hobby.

Cheers,
Colin

https://coastalchalet.co.uk
